version: '3'
services:
  # 可自定义
  web:
    # 可自定义，作为docker构建容器镜像的标签
    image: myweb:v1.2
    # 可自定义，作为挂载的目录
    volumes:
      - ./:/L-Web
    ports:
      - 5000:5000
    command: /bin/sh /L-Web/tools/run.sh
